pipeline:
  build:
    image: dunecommunity/gitlabci_dockerindocker-dockerindocker
    commands:
      - git submodule status
      - ./bin/check_environments.py
      - echo $DOCKER_PW | docker login --username="$DOCKER_USER" --password-stdin
      - pip3 install -U docker jinja2 docopt
      - .ci/templates/update.py --nc 'no message'
      - cd dune-xt-$TRAVIS_MODULE_NAME
      - git diff

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ docker_user, docker_pw ]

matrix:
  TRAVIS_MODULE_NAME:
    - common
    - la
    - functions
    - data
    - grid 
