pipeline:
  check:
    image: dunecommunity/gitlabci_dockerindocker-dockerindocker
    commands:
      - git submodule status
      - ./bin/check_environments.py
      - pip3 install -U docker jinja2 docopt
      - .ci/templates/update.py --nd --nc 'no message'
      - for i in $( ls -d dune-xt-* ) ; do cd $i ; git diff ; cd - ; done

  docker:
    image: dunecommunity/gitlabci_dockerindocker-dockerindocker
    commands:
      - echo $DOCKER_PW | docker login --username="$DOCKER_USER" --password-stdin
      - pip3 install -U docker jinja2 docopt
      - .ci/templates/update.py --nc 'no message'

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ docker_user, docker_pw ]
    when:
      event: push

  notify:
    image: drillster/drone-email
    host: mail.milk.pm
    from: drone@pymor.org
    when:
      status: [ changed, failure ]
    secrets:  [ email_username, email_password ]
