# This file is part of the dune-xt project:
#   https://github.com/dune-community/dune-xt-super
# The copyright lies with the authors of this file (see below).
# License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
# Authors:
#   Rene Milk       (2016)

sudo: required
dist: trusty
language: generic

script:
    - cd ${TRAVIS_BUILD_DIR}
    - git submodule update --init --recursive
    - git submodule status

before_script:
    - pushd ${TRAVIS_BUILD_DIR}/.travis
    - openssl aes-256-cbc -K $encrypted_862ca47045d1_key -iv $encrypted_862ca47045d1_iv -in github_deploy.rsa.enc -out github_deploy.rsa -d
    - popd

notifications:
  email:
    on_success: change
    on_failure: change
