# do not build prs at all
pr:
  branches:
    exclude:
    - '*'

stages:
  - stage: base
    displayName: base image
    jobs:
      - template: /.ci/azure-job-template.yml
        parameters:
          module_name: 'BASE'
  - stage: modules
    displayName: 'module images'
    dependsOn: base
    jobs:
    - template: /.ci/azure-job-template.yml
      parameters:
        module_name: 'dune-xt'
        job_name: 'common'
        project_id: 'fe89f0b2-b715-4c9d-af77-220e72e5f760'
    - template: /.ci/azure-job-template.yml
      parameters:
        module_name: 'dune-xt-data'
        job_name: 'data'
        project_id: '1a74e769-288c-4884-9cd4-190fc3bc4d54'
    - job: super
      timeoutInMinutes: 0
      pool:
        vmImage: 'ubuntu-16.04'
      variables:
        BASE: debian
        IMAGE: dunecommunity/xt-super_debian:$(Build.SourceVersion)
        ALTTAG: dunecommunity/xt-super_debian:$(Build.SourceBranchName)
      steps:
        - checkout: self
          submodules: true
        - task: Docker@1
          displayName: Container registry login
          inputs:
            command: login
            containerregistrytype: Container Registry
            dockerRegistryEndpoint: dockerhub
        - script: |
            docker build --build-arg BASE=${BASE} -t ${IMAGE} -f .ci/shared/docker/super_docker/Dockerfile .
            docker tag ${IMAGE} ${ALTTAG}
            docker push ${IMAGE}
            docker push ${ALTTAG}
