parameters:
  module_name: 'BASE'
  job_name: 'base'
  project_id: ''

jobs:
- job: ${{ parameters.job_name }}
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - checkout: self
      submodules: true
    - task: Docker@1
      displayName: Container registry login
      inputs:
        command: login
        containerregistrytype: Container Registry
        dockerRegistryEndpoint: dockerhub
    - script: |
        sudo apt install -y openssh-client rsync git file bash python3-pip python3-setuptools
        sudo pip3 install -U docker jinja2 docopt
        .ci/shared/docker/update_test_dockers.py -v ${{ parameters.module_name }}
- job: trigger_${{ parameters.job_name }}
  timeoutInMinutes: 10
  dependsOn: ${{ parameters.job_name }}
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: TriggerPipeline@1
      condition: ne(variables['Agent.JobName'], 'trigger_base')
      displayName: 'trigger downstream build'
      inputs:
        serviceConnection: 'devops_api'
        project: '${{ parameters.project_id }}'
        Pipeline: 'Build'
        buildDefinition: 'dune-community.${{ parameters.module_name }}'
        Branch: 'master'
