parameters:
  module_name: 'BASE'
  job_name: 'base'

jobs:
- job: ${{ parameters.jobname_name }}
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - checkout: self
      submodules: true
    - task: Docker@1
      displayName: Container registry login
      inputs:
        command: login
        containerregistrytype: Container Registry
        dockerRegistryEndpoint: dockerhub
    - script: |
        sudo apt install -y openssh-client rsync git file bash python3-pip python3-setuptools
        sudo pip3 install -U docker jinja2 docopt
        .ci/shared/docker/update_test_dockers.py -v ${{ parameters.module_name }}
