stages:
  - base
  - modules

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.test_base:
    retry:
        max: 2
        when:
            - runner_system_failure
            - stuck_or_timeout_failure
            - api_failure
    only: ['branches', 'tags', 'triggers', 'merge-requests']
    except:
        - /^staging/.*$/i

.docker-in-docker:
    tags:
      - docker-in-docker
    extends: .test_base
    retry:
        max: 2
        when:
            - always
    image: harbor.uni-muenster.de/proxy-docker/library/docker:stable
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
    before_script:
        - apk --update add py3-pip openssh-client rsync git file bash python3 curl make
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - pip3 install docopt six docker
        - alias python=python3
        - alias pip=pip3
    services:
        - name: harbor.uni-muenster.de/proxy-docker/library/docker:dind
          alias: docker
    environment:
        name: unsafe

base image:
  stage: base
  extends: .docker-in-docker
  script: .ci/shared/docker/update_test_dockers.py -v BASE

xt:
  stage: modules
  extends: .docker-in-docker
  script: .ci/shared/docker/update_test_dockers.py -v dune-xt
super:
  stage: modules
  extends: .docker-in-docker
  variables:
    BASE: debian
    IMAGE: ${CI_REGISTRY_IMAGE}/super_debian:${CI_COMMIT_REF_NAME}
    ALTTAG: ${CI_REGISTRY_IMAGE}/super_debian:${CI_COMMIT_SHA}
  script:
      - docker build --build-arg BASE=${BASE} -t ${IMAGE} -f .ci/shared/docker/super_docker/Dockerfile .
      - docker tag ${IMAGE} ${ALTTAG}
      - docker push ${IMAGE}
      - docker push ${ALTTAG}
