# This file is part of the dune-xt project:
#   https://github.com/dune-community/dune-xt-super
# The copyright lies with the authors of this file (see below).
# License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
# Authors:
#   Rene Milk       (2017)

image: dunecommunity/gitlabci_dockerindocker

stage:
    before_script:
    - pip3 install docker

    script:
    - git submodule update --init --recursive
    - git submodule status
    - export TRAVIS_BRANCH=${CI_COMMIT_REF_NAME}
    - export TRAVIS=${GITLAB_CI}
    - python3 -c "from configparser import SafeConfigParser as sf ; f = sf() ; f.readfp(open('external-libraries.cfg', 'rt'))"
    - |
        docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
        python3 ./.ci/templates/update.py "updated travis.ymls from CI"

# notifications: Not implemented, see
# https://gitlab.com/gitlab-org/gitlab-ce/issues/23404

services:
- docker:dind

